package typedbehavior

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"reflect"
	"testing"
)

type propertyObservationLiteral struct {
	input string
	want  PropertyQuotedObservation
}

// These nine expected values are authored literally, never generated by a
// candidate, full-contract role, original outcome or original oracle accessor.
// They are source-preparation unit fixtures, not new independent requests or
// official cohort observations.
func propertyObservationLiterals() ([2]propertyObservationLiteral, [2]propertyObservationLiteral, [5]propertyObservationLiteral) {
	quoted := [2]propertyObservationLiteral{
		{`"a,b",c`, PropertyQuotedObservation{Error: PropertyQuotedOK, Count: 2, Tokens: [8]string{"a,b", "c"}}},
		{`ab"c,d"ef`, PropertyQuotedObservation{Error: PropertyQuotedOK, Count: 1, Tokens: [8]string{"abc,def"}}},
	}
	escaped := [2]propertyObservationLiteral{
		{`a\,b,c`, PropertyQuotedObservation{Error: PropertyQuotedOK, Count: 2, Tokens: [8]string{"a,b", "c"}}},
		{`a\\,b`, PropertyQuotedObservation{Error: PropertyQuotedOK, Count: 2, Tokens: [8]string{`a\`, "b"}}},
	}
	syntax := [5]propertyObservationLiteral{
		{`"a,b`, PropertyQuotedObservation{Error: PropertyQuotedSyntax}},
		{`a\`, PropertyQuotedObservation{Error: PropertyQuotedSyntax}},
		{`a,b\`, PropertyQuotedObservation{Error: PropertyQuotedSyntax}},
		{`"a\`, PropertyQuotedObservation{Error: PropertyQuotedSyntax}},
		{`a,"b`, PropertyQuotedObservation{Error: PropertyQuotedSyntax}},
	}
	return quoted, escaped, syntax
}

func TestPropertyObservationNineLiteralSourceDifferences(t *testing.T) {
	quoted, escaped, syntax := propertyObservationLiterals()
	properties := [3][]propertyObservationLiteral{quoted[:], escaped[:], syntax[:]}
	// Each row is a property-specific expectation. The whole-contract wrong
	// sources intentionally pass some properties. No sourceSpecs role is read.
	controls := [4]struct {
		id        string
		wantMatch [3]bool
	}{
		{"quoted-correct", [3]bool{true, true, true}},
		{"quoted-literal-comma", [3]bool{false, false, false}},
		{"quoted-inside-escape", [3]bool{true, false, false}},
		{"quoted-partial-error", [3]bool{true, true, false}},
	}
	for _, source := range controls {
		t.Run(source.id, func(t *testing.T) {
			for property, literals := range properties {
				allMatch := true
				for _, literal := range literals {
					got, err := ObserveQuotedProperty(source.id, literal.input)
					if err != nil || got.Panicked {
						t.Fatalf("property %d lost supported observation: %+v; %v", property, got, err)
					}
					if got != literal.want {
						allMatch = false
					}
					again, err := ObserveQuotedProperty(source.id, literal.input)
					if err != nil || again != got {
						t.Fatalf("property %d observation was not stable", property)
					}
				}
				if allMatch != source.wantMatch[property] {
					t.Fatalf("property %d match=%t; want=%t", property, allMatch, source.wantMatch[property])
				}
			}
		})
	}
}

func TestPropertyObservationOutsideEscapePreservesParity(t *testing.T) {
	_, escaped, _ := propertyObservationLiterals()
	got, err := ObserveQuotedProperty("quoted-inside-escape", escaped[0].input)
	if err != nil || got != (PropertyQuotedObservation{
		Error: PropertyQuotedOK, Count: 3, Tokens: [8]string{`a\`, "b", "c"},
	}) {
		t.Fatalf("outside-only failure was not preserved: %+v; %v", got, err)
	}
	if got == escaped[0].want {
		t.Fatal("splitting an escaped comma satisfied the property")
	}
	for _, id := range [2]string{"quoted-correct", "quoted-partial-error"} {
		got, err := ObserveQuotedProperty(id, escaped[1].input)
		if err != nil || got != escaped[1].want {
			t.Fatalf("two backslashes swallowed the following delimiter: %s; %+v; %v", id, got, err)
		}
	}
}

func TestPropertyObservationSyntaxErrorIsRequiredAndOutputFullyEmpty(t *testing.T) {
	_, _, syntax := propertyObservationLiterals()
	literal := syntax[2] // a,b\; authored malformed input requires syntax error.
	for _, id := range [2]string{"quoted-literal-comma", "quoted-inside-escape"} {
		got, err := ObserveQuotedProperty(id, literal.input)
		if err != nil || got.Error != PropertyQuotedOK || got == literal.want {
			t.Fatalf("omitted syntax error was not exposed: %s; %+v; %v", id, got, err)
		}
	}
	partial, err := ObserveQuotedProperty("quoted-partial-error", literal.input)
	if err != nil || partial != (PropertyQuotedObservation{
		Error: PropertyQuotedSyntax, Count: 2, Tokens: [8]string{"a", "b"},
	}) || partial == literal.want {
		t.Fatalf("partial syntax output was hidden: %+v; %v", partial, err)
	}
	correct, err := ObserveQuotedProperty("quoted-correct", literal.input)
	if err != nil || correct != literal.want || correct.Tokens != ([8]string{}) {
		t.Fatalf("complete zero output was not observed: %+v; %v", correct, err)
	}
	// A Count-only check must not be substituted for the scoped observation.
	// These are forged observation values, not additional candidate controls.
	residual := correct
	residual.Tokens[7] = "residual"
	if residual.Count != 0 || residual == literal.want {
		t.Fatal("an unused residual slot satisfied the zero-output observation")
	}
	panicked := correct
	panicked.Panicked = true
	if panicked == literal.want {
		t.Fatal("a captured panic satisfied a required no-panic observation")
	}
}

func TestPropertyObservationUnknownSourceReturnsFixedErrorAndNoObservation(t *testing.T) {
	for _, source := range [5]string{"", "unregistered-source", "Quoted-correct", "quoted-correct ", "lifecycle-correct"} {
		got, err := ObserveQuotedProperty(source, "private-marker-not-returned")
		if got != (PropertyQuotedObservation{}) || err == nil || err.Error() != "property_observation_source_not_registered" {
			t.Fatalf("unknown source supplied an observation or varying error: %+v; %v", got, err)
		}
	}
}

func TestPropertyObservationValuesAndProvenanceAreOwned(t *testing.T) {
	quoted, _, _ := propertyObservationLiterals()
	got, err := ObserveQuotedProperty("quoted-partial-error", quoted[0].input)
	if err != nil || got != quoted[0].want {
		t.Fatalf("observation unavailable: %+v; %v", got, err)
	}
	got.Tokens[0] = "changed"
	got.Count = 0
	got.Error = PropertyQuotedSyntax
	again, err := ObserveQuotedProperty("quoted-partial-error", quoted[0].input)
	if err != nil || again != quoted[0].want {
		t.Fatal("a caller changed a later observation")
	}
	artifacts := PropertyObservationSourceArtifacts()
	if len(artifacts) != 1 || artifacts[0].Name != "property_observation.go" {
		t.Fatalf("adapter source evidence shape: %+v", artifacts)
	}
	raw, err := os.ReadFile("property_observation.go")
	if err != nil {
		t.Fatal(err)
	}
	hash := sha256.Sum256(raw)
	if artifacts[0].SHA256 != hex.EncodeToString(hash[:]) {
		t.Fatal("compiled adapter evidence differs from actual source")
	}
	want := artifacts[0]
	artifacts[0].Name, artifacts[0].SHA256 = "changed", "changed"
	if again := PropertyObservationSourceArtifacts(); len(again) != 1 || again[0] != want {
		t.Fatal("a caller mutated adapter provenance")
	}
}

func TestPropertyObservationPreservesEightHistoricalSourceArtifacts(t *testing.T) {
	want := []SourceArtifact{
		{"spec.go", "013a486ecc1d28913c2dda8cf74b3068dcb193d8b77e534dc62e2f87b9ee6b80"},
		{"state.go", "35324ed595bcf384c484f33d98c6866164bebb2b636986ee8ea51bb979bdad7c"},
		{"flow.go", "ea7f09d31e15e561173932ac0bb61db17746cdce929e0f976d97994d282d898b"},
		{"source.go", "5bdb4dd6509c1913bb1b728575b0a92e4c79ac8db0e2851b44d2ab6f3c1ca914"},
		{"dataset.go", "28c63979603e9e231827ca3e80f7a8367da5dc4ea5c7afea72c0a91176227b73"},
		{"fixtures.go", "6ad2707048502b82d27d839bb053154b6c284eef703e89b5386ac6672ac036e0"},
		{"audit.go", "a5db68399561a28e91710eae9936c9976b8457eba6f91979cc2fe54cc574cc00"},
		{"groups.go", "76745eb94700b6e7545b9ba35e5b4ae5c8b714c31fd2626ccfabd9da63b1e363"},
	}
	if got := SourceArtifacts(); !reflect.DeepEqual(got, want) {
		t.Fatalf("historical compiled source evidence changed: %+v", got)
	}
	PropertyObservationSourceArtifacts()
	if got := SourceArtifacts(); !reflect.DeepEqual(got, want) {
		t.Fatal("querying adapter evidence changed historical provenance")
	}
}
