// Copyright 2026 SWYG. SPDX-License-Identifier: Apache-2.0
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/teamswyg/laya-tools/pkg/statehintclaims"
	"github.com/teamswyg/laya-tools/pkg/statehintclaimsmlp"
	"math"
	"os"
	"strings"
	"testing"
	"time"
)

func number(i int) *int { return &i }
func encodeRows(t *testing.T, rows []rawRow) []byte {
	t.Helper()
	var b bytes.Buffer
	e := json.NewEncoder(&b)
	for _, r := range rows {
		if e.Encode(r) != nil {
			t.Fatal("encode owned fixture")
		}
	}
	return b.Bytes()
}
func encode(t *testing.T, v any) []byte {
	t.Helper()
	b, e := json.Marshal(v)
	if e != nil {
		t.Fatal(e)
	}
	return b
}
func writeOwned(t *testing.T, name string, data []byte) {
	t.Helper()
	if os.WriteFile(name, data, 0600) != nil {
		t.Fatal("write owned fixture")
	}
}

// The test generates every word, ID and label itself. Repetition exercises
// owned numeric plumbing and has no semantic or model-quality meaning.
func ownedRows(split string, families int) []rawRow {
	rows := make([]rawRow, 0, 2*families)
	for i := 0; i < families; i++ {
		family := fmt.Sprintf("owned-%s-%03d", split, i)
		group := fmt.Sprintf("owned-%s-group-%03d", split, i/3)
		for _, locale := range []string{"ko", "en"} {
			text := "직접 작성한 숫자시험 문장입니다."
			if locale == "en" {
				text = "Amber kite original owned numerical fixture."
			}
			r := rawRow{Schema: rowSchema, ID: family + "-" + locale, Family: family, Group: group, Split: split, Locale: locale, Text: text, RubricSHA: strings.Repeat("b", 64), AnnotationSource: "ai_semantic_reference"}
			for h := 0; h < 3; h++ {
				target := statehintclaims.States()[(i+h)%3]
				r.Targets = append(r.Targets, string(target))
				end := len(text)
				if target == statehintclaims.False {
					end = 0
				}
				r.Evidence = append(r.Evidence, evidenceInput{number(0), number(end), "Owned numerical fixture; no semantic quality evidence."})
			}
			rows = append(rows, r)
		}
	}
	return rows
}

// Every byte/word/target below is generated by the test. Header histories are
// synthetic plumbing fixtures, not claims that a model has actually been fit.
func ownedArtifact(t *testing.T, mlp bool, steps uint64) []byte {
	t.Helper()
	var b bytes.Buffer
	if mlp {
		if statehintclaimsmlp.NewModel().Save(&b) != nil {
			t.Fatal("owned RCM")
		}
	} else if statehintclaims.NewModel().Save(&b) != nil {
		t.Fatal("owned RSC")
	}
	data := append([]byte(nil), b.Bytes()...)
	binary.LittleEndian.PutUint64(data[16:24], steps)
	if mlp {
		binary.LittleEndian.PutUint32(data[152:156], 1680)
	}
	end := len(data) - sha256.Size
	checksum := sha256.Sum256(data[:end])
	copy(data[end:], checksum[:])
	return data
}

type fixture struct {
	training, evaluation, metadata, receipt, reference, linear, mlp []byte
	refs                                                            receipt
	manifest                                                        manifest
}

func ownedFixture(t *testing.T) fixture {
	t.Helper()
	training := ownedRows("fit", 840)
	eval := ownedRows("dev", 180)
	meta := strataInput{Schema: strataSchema}
	for i, r := range eval {
		stratum := "contrast"
		if i >= 240 {
			stratum = "general"
		}
		meta.Rows = append(meta.Rows, stratumRow{r.ID, r.Family, r.Group, r.Locale, stratum})
	}
	f := fixture{training: encodeRows(t, training), evaluation: encodeRows(t, eval), metadata: encode(t, meta), reference: ownedArtifact(t, false, 4240), linear: ownedArtifact(t, false, 2120), mlp: ownedArtifact(t, true, 2120)}
	c, e := metadataCounts(meta.Rows, true)
	if e != nil {
		t.Fatal(e)
	}
	f.refs = receipt{Schema: receiptSchema, TrainingSHA: digest(f.training), EvaluationSHA: digest(f.evaluation), EvaluationBytes: int64(len(f.evaluation)), StrataSHA: digest(f.metadata), RowSchema: rowSchema, AnnotationSource: "ai_semantic_reference", ReferenceStatus: "ai_authored_independently_ai_reviewed_human_pending", Locales: [2]string{"ko", "en"}, Heads: headOrder(), States: statehintclaims.States(), EvaluationCounts: c}
	for l := 0; l < 2; l++ {
		for h := 0; h < 3; h++ {
			for k := 0; k < 3; k++ {
				f.refs.ContrastFamilies[l][h][k] = 40
				f.refs.ContrastLineages[l][h][k] = 40
			}
		}
	}
	f.receipt = encode(t, f.refs)
	f.manifest = manifest{digest(f.training), digest(f.reference)}
	return f
}
func (f fixture) write(t *testing.T) {
	t.Helper()
	for _, file := range []struct {
		name string
		data []byte
	}{{"training.jsonl", f.training}, {"evaluation.jsonl", f.evaluation}, {"strata.json", f.metadata}, {"receipt.json", f.receipt}, {"reference.rsc", f.reference}} {
		writeOwned(t, file.name, file.data)
	}
}
func (f fixture) args() []string {
	return []string{"--training", "training.jsonl", "--training-sha256", digest(f.training), "--evaluation", "evaluation.jsonl", "--evaluation-sha256", f.refs.EvaluationSHA, "--strata", "strata.json", "--strata-sha256", digest(f.metadata), "--receipt", "receipt.json", "--receipt-sha256", digest(f.receipt), "--reference", "reference.rsc", "--reference-sha256", digest(f.reference)}
}
func invoke(t *testing.T, f fixture, ops studyOperations, extra ...string) ([]byte, error) {
	t.Helper()
	var out, errOut bytes.Buffer
	e := runWithOperations(append(f.args(), extra...), &out, &errOut, f.manifest, ops)
	if errOut.Len() != 0 {
		t.Fatal("unexpected diagnostic data")
	}
	return out.Bytes(), e
}
func forbiddenOperations(t *testing.T) studyOperations {
	t.Helper()
	return studyOperations{
		fitLinear: func([]statehintclaims.Sample) (modelAdapter, fitReport, error) {
			t.Fatal("unexpected linear Fit")
			return modelAdapter{}, fitReport{}, errStudy
		},
		fitMLP: func([]statehintclaims.Sample) (modelAdapter, fitReport, error) {
			t.Fatal("unexpected MLP Fit")
			return modelAdapter{}, fitReport{}, errStudy
		},
		loadLinear: func([]byte, uint64) (modelAdapter, error) {
			t.Fatal("unexpected linear Load")
			return modelAdapter{}, errStudy
		},
		loadMLP: func([]byte) (modelAdapter, error) { t.Fatal("unexpected MLP Load"); return modelAdapter{}, errStudy },
	}
}
func TestCheckNeverReadsSealedEvaluationOrReferenceBodyOrCreatesFiles(t *testing.T) {
	t.Chdir(t.TempDir())
	f := ownedFixture(t)
	// Both sealed bodies are deliberately corrupt/unreadable and unhashable.
	f.evaluation = bytes.Repeat([]byte{'x'}, len(f.evaluation))
	f.reference = bytes.Repeat([]byte{'x'}, linearBytes)
	f.manifest.reference = digest(f.reference)
	f.write(t)
	for _, name := range []string{"evaluation.jsonl", "reference.rsc"} {
		if os.Chmod(name, 0000) != nil {
			t.Fatal("seal mode")
		}
	}
	out, e := invoke(t, f, forbiddenOperations(t), "--check")
	if e != nil || !bytes.Contains(out, []byte("no evaluation or prior body read")) {
		t.Fatal("check crossed read/model barrier", e)
	}
	if _, e := os.Stat(".cache"); !os.IsNotExist(e) {
		t.Fatal("check created output")
	}
	for _, extra := range [][]string{{"--check", "--out", anchor + "/bad"}, {"--check", "--cpu-profile"}, {"--epochs", "1"}, {"--seed", "1"}, {"--selection"}, {"--model", "private-marker"}, {"--check", "--manifest", "private-marker"}, {"--learning-rate", ".2"}} {
		out, e := invoke(t, f, forbiddenOperations(t), extra...)
		if e == nil || len(out) != 0 || strings.Contains(e.Error(), "private-marker") {
			t.Fatal("CLI admitted override or leaked input")
		}
	}
	var output, errorOutput bytes.Buffer
	if run(append(f.args(), "--check"), &output, &errorOutput) == nil {
		t.Fatal("frozen pins accepted synthetic alternative")
	}
	if os.Remove("evaluation.jsonl") != nil {
		t.Fatal("remove owned evaluation")
	}
	if _, e := invoke(t, f, forbiddenOperations(t), "--check"); e == nil {
		t.Fatal("missing sealed leaf accepted")
	}
}
func TestAllRoleAliasesRejectedBeforeAnyBodyRead(t *testing.T) {
	t.Chdir(t.TempDir())
	f := ownedFixture(t)
	f.evaluation = bytes.Repeat([]byte{'x'}, linearBytes)
	f.write(t)
	if os.Chmod("evaluation.jsonl", 0000) != nil || os.Link("evaluation.jsonl", "evaluation-hardlink") != nil {
		t.Fatal("owned alias")
	}
	for _, role := range []string{"--training", "--strata", "--receipt", "--reference"} {
		for _, alias := range []string{"evaluation.jsonl", "evaluation-hardlink"} {
			for _, mode := range []string{"check", "actual"} {
				args := f.args()
				for i := 0; i < len(args); i += 2 {
					if args[i] == role {
						args[i+1] = alias
					}
				}
				if mode == "check" {
					args = append(args, "--check")
				} else {
					args = append(args, "--out", anchor+"/rejected")
				}
				var out, errOut bytes.Buffer
				e := runWithOperations(args, &out, &errOut, f.manifest, forbiddenOperations(t))
				if !errors.Is(e, errEvaluationAlias) || out.Len() != 0 || errOut.Len() != 0 {
					t.Fatalf("alias guard did not precede all reads: %s %s %s %v", role, alias, mode, e)
				}
			}
		}
	}
	if _, e := os.Stat(".cache"); !os.IsNotExist(e) {
		t.Fatal("alias created output")
	}
	// Also disallow cross-role aliases that do not involve the sealed evaluation.
	args := f.args()
	for i := 0; i < len(args); i += 2 {
		if args[i] == "--strata" {
			args[i+1] = "training.jsonl"
		}
	}
	var out, errOut bytes.Buffer
	if e := runWithOperations(append(args, "--check"), &out, &errOut, f.manifest, forbiddenOperations(t)); !errors.Is(e, errInputAlias) {
		t.Fatal("non-evaluation alias admitted", e)
	}
}
func TestSnapshotsPathsAndPrivateOutput(t *testing.T) {
	t.Chdir(t.TempDir())
	f := ownedFixture(t)
	f.write(t)
	root, e := os.OpenRoot(".")
	if e != nil {
		t.Fatal(e)
	}
	defer root.Close()
	for _, name := range []string{"../evaluation.jsonl", "./evaluation.jsonl", "evaluation.jsonl/", "/evaluation.jsonl", "a\\b"} {
		if _, e := inspectInput(root, name, inputBudget); e == nil {
			t.Fatal("non-local/noncanonical name admitted")
		}
	}
	if os.Mkdir("regular", 0700) != nil || os.Symlink("regular", "linked") != nil {
		t.Fatal("owned ancestor")
	}
	writeOwned(t, "regular/input", f.training)
	if _, e := readPinned(root, "linked/input", digest(f.training), inputBudget, 0); e == nil {
		t.Fatal("symlink ancestor admitted")
	}
	if os.Symlink("evaluation.jsonl", "eval-link") != nil {
		t.Fatal("owned leaf symlink")
	}
	if _, e := inspectInput(root, "eval-link", inputBudget); e == nil {
		t.Fatal("symlink leaf admitted")
	}
	snapshots, e := preflightInputs(root, pins{trainingName: "training.jsonl", evaluationName: "evaluation.jsonl", strataName: "strata.json", receiptName: "receipt.json", referenceName: "reference.rsc"})
	if e != nil {
		t.Fatal(e)
	}
	role := inputRole{"training.jsonl", digest(f.training), inputBudget, 0}
	changed := snapshots[role.name].ModTime().Add(time.Second)
	if os.Chtimes(role.name, changed, changed) != nil {
		t.Fatal("owned timestamp")
	}
	if _, e := readSnapshot(root, role, snapshots[role.name]); e == nil {
		t.Fatal("preflight body snapshot drift admitted")
	}
	if os.Remove(role.name) != nil || os.Link("evaluation.jsonl", role.name) != nil {
		t.Fatal("owned replacement")
	}
	if _, e := readSnapshot(root, role, snapshots[role.name]); e == nil {
		t.Fatal("post-preflight hardlink replacement body read")
	}
	if os.Symlink("regular", ".cache") != nil {
		t.Fatal("owned output symlink")
	}
	if out, e := privateOutput(root, anchor+"/reject"); e == nil {
		out.Close()
		t.Fatal("symlink output admitted")
	}
}

// The phase test substitutes owned synthetic artifact bytes for Fit. It invokes
// no actual training; native Save/Load/Predict/Scores exercise only owned text.
func ownedOperations(t *testing.T, f fixture, events *[]string) studyOperations {
	t.Helper()
	native := nativeOperations()
	expected, _ := prepare(f.training, "fit")
	verify := func(samples []statehintclaims.Sample) {
		if len(samples) != 1680 {
			t.Fatal("training denominator")
		}
		for i, sample := range samples {
			if sample.Text != expected.rows[i].Text || sample.Targets != expected.rows[i].labels {
				t.Fatal("evaluation/metadata entered training")
			}
		}
	}
	ledgerAt := func(calls int) {
		data, e := os.ReadFile(anchor + "/owned/fit-consumption.json")
		var ledger consumption
		if e != nil || json.Unmarshal(data, &ledger) != nil || ledger.FitCalls != calls {
			t.Fatal("fit consumed after invocation instead of before", calls, e)
		}
	}
	r := fitReport{1680, 40, 2120, 2120, 1.1, "fresh_zero", 1729, 32, .001, .01}
	return studyOperations{
		fitLinear: func(samples []statehintclaims.Sample) (modelAdapter, fitReport, error) {
			verify(samples)
			ledgerAt(1)
			*events = append(*events, "fit_linear")
			m, e := native.loadLinear(f.linear, 2120)
			return m, r, e
		},
		fitMLP: func(samples []statehintclaims.Sample) (modelAdapter, fitReport, error) {
			verify(samples)
			ledgerAt(2)
			if data, e := os.ReadFile(anchor + "/owned/linear.rsc"); e != nil || !bytes.Equal(data, f.linear) {
				t.Fatal("linear not saved before MLP")
			}
			*events = append(*events, "fit_mlp")
			m, e := native.loadMLP(f.mlp)
			mr := r
			mr.Initialization = statehintclaimsmlp.Initialization
			return m, mr, e
		},
		loadLinear: func(data []byte, steps uint64) (modelAdapter, error) {
			if steps == 4240 {
				for _, name := range []string{"linear.rsc", "mlp.rcm"} {
					if _, e := os.Stat(anchor + "/owned/" + name); e != nil {
						t.Fatal("prior load before both artifacts", e)
					}
				}
				*events = append(*events, "load_prior")
			} else {
				*events = append(*events, "reload_linear")
			}
			return native.loadLinear(data, steps)
		},
		loadMLP: func(data []byte) (modelAdapter, error) {
			*events = append(*events, "reload_mlp")
			return native.loadMLP(data)
		},
	}
}
func TestOwnedTwoFitPhaseParityPrivateAggregate(t *testing.T) {
	t.Chdir(t.TempDir())
	f := ownedFixture(t)
	f.write(t)
	var events []string
	if _, e := invoke(t, f, ownedOperations(t, f, &events), "--out", anchor+"/owned", "--cpu-profile"); e != nil {
		t.Fatal("owned phase run", e)
	}
	if strings.Join(events, ",") != "fit_linear,fit_mlp,load_prior,reload_linear,reload_mlp" {
		t.Fatal("fixed phase order/count", events)
	}
	data, e := os.ReadFile(anchor + "/owned/report.json")
	var report studyReport
	if e != nil || json.Unmarshal(data, &report) != nil {
		t.Fatal("owned report", e)
	}
	if report.FitCalls != 2 || report.Recipe != fixedRecipe() || !report.FitsSavedBeforeEvaluation || report.PriorReference.TrainingSteps != 4240 || report.ColdLinear.TrainingSteps != 2120 || report.ColdMLP.TrainingSteps != 2120 || report.PriorEqualBudget || report.Selection || report.Calibration || report.QualificationChanged || report.Qualified || report.OriginalQualified || report.CalTestAccessed || report.StateWrites != 0 || report.OSRSSMeasured {
		t.Fatal("fixed budget/research boundary")
	}
	for i, r := range report.Fits {
		if r.TrainingSteps != 2120 || r.Batches != 2120 || r.Epochs != 40 || r.Samples != 1680 || r.Seed != 1729 {
			t.Fatal("recipe count", i)
		}
	}
	for _, candidate := range []candidateReport{report.ColdLinear, report.ColdMLP} {
		if !candidate.ReloadByteExact || !candidate.ReloadPredictExact || !candidate.ReloadScoresExact || !candidate.ReadOnlyExact || candidate.PredictionCalls != 360 || candidate.ScoreCalls != 360 || candidate.ReloadPredictionCalls != 360 || candidate.ReloadScoreCalls != 360 {
			t.Fatal("save/load observation parity")
		}
	}
	if report.ColdLinear.ArtifactBytes != 73988 || report.ColdMLP.ArtifactBytes != 131972 || report.Primary.Lineages != [2]int{40, 20} || !report.PriorReference.ReadOnlyExact || !report.CPUProfile || report.FitLossMeaning != "mean_online_fit_trajectory_loss_across_all_epochs_not_final_evaluation_ce" {
		t.Fatal("artifact/bootstrap/loss/resource report")
	}
	for _, eval := range []evaluationReport{report.ColdLinearEvaluation, report.ColdMLPEvaluation, report.PriorEvaluation} {
		if eval.Rows != 360 {
			t.Fatal("evaluation count")
		}
		for _, l := range eval.Locales {
			if l.Rows != 180 || l.UnknownTargetCount != 180 {
				t.Fatal("locale/unknown count")
			}
			for h := 0; h < 3; h++ {
				if l.ReferenceCounts[h] != [3]int{60, 60, 60} || l.ReferenceLineages[h] != [3]int{60, 60, 60} || l.TrueFalsePositive[h] != l.TrueOnFalse[h]+l.TrueOnUnknown[h] {
					t.Fatal("reference/fp support")
				}
			}
		}
	}
	for _, marker := range []string{"owned-dev-000", "owned-fit-000", "Amber kite", "직접 작성한", "Owned numerical fixture", "reference.rsc", "evaluation.jsonl", "training.jsonl"} {
		if bytes.Contains(data, []byte(marker)) {
			t.Fatal("text/id/path leakage")
		}
	}
	for _, name := range []string{"linear.rsc", "mlp.rcm", "report.json", "fit-consumption.json", "cpu.pprof"} {
		st, e := os.Stat(anchor + "/owned/" + name)
		if e != nil || st.Mode().Perm() != 0600 || st.Size() == 0 {
			t.Fatal("private output", name, e)
		}
	}
	st, e := os.Stat(anchor + "/owned")
	if e != nil || st.Mode().Perm() != 0700 {
		t.Fatal("private directory")
	}
	if _, e := invoke(t, f, forbiddenOperations(t), "--out", anchor+"/owned"); e == nil {
		t.Fatal("retry reused output")
	}
}
func TestFailurePreservesEachConsumedFitAndPriorSavedModel(t *testing.T) {
	for _, failure := range []string{"first_fit", "second_fit", "bad_evaluation", "bad_prior"} {
		t.Run(failure, func(t *testing.T) {
			t.Chdir(t.TempDir())
			f := ownedFixture(t)
			if failure == "bad_evaluation" {
				f.evaluation = bytes.Repeat([]byte{'x'}, len(f.evaluation))
				f.refs.EvaluationSHA = digest(f.evaluation)
				f.receipt = encode(t, f.refs)
			}
			if failure == "bad_prior" {
				f.reference = bytes.Repeat([]byte{'x'}, linearBytes)
				f.manifest.reference = digest(f.reference)
			}
			f.write(t)
			var events []string
			ops := ownedOperations(t, f, &events)
			if failure == "first_fit" {
				ops.fitLinear = func([]statehintclaims.Sample) (modelAdapter, fitReport, error) {
					return modelAdapter{}, fitReport{}, errStudy
				}
			}
			if failure == "second_fit" {
				ops.fitMLP = func([]statehintclaims.Sample) (modelAdapter, fitReport, error) {
					return modelAdapter{}, fitReport{}, errStudy
				}
			}
			if _, e := invoke(t, f, ops, "--out", anchor+"/owned"); e == nil {
				t.Fatal("accepted injected failure")
			}
			data, e := os.ReadFile(anchor + "/owned/fit-consumption.json")
			var ledger consumption
			if e != nil || json.Unmarshal(data, &ledger) != nil || !ledger.NoRetry || ledger.Status != "failed_after_fit_invocation_consumed" {
				t.Fatal("failure consumption lost", e)
			}
			want := 2
			if failure == "first_fit" {
				want = 1
			}
			if ledger.FitCalls != want || ledger.FitInvocations[0] != 1 || want == 2 && ledger.FitInvocations[1] != 1 {
				t.Fatal("fit consumption count", ledger)
			}
			if failure != "first_fit" {
				data, e := os.ReadFile(anchor + "/owned/linear.rsc")
				if e != nil || !bytes.Equal(data, f.linear) {
					t.Fatal("prior completed linear lost", e)
				}
			}
			if failure == "bad_evaluation" || failure == "bad_prior" {
				data, e := os.ReadFile(anchor + "/owned/mlp.rcm")
				if e != nil || !bytes.Equal(data, f.mlp) {
					t.Fatal("completed MLP lost", e)
				}
			}
			if failure == "bad_evaluation" && ledger.Phase != "evaluation_schema_parse" || failure == "bad_prior" && ledger.Phase != "prior_reference_numeric_load" {
				t.Fatal("failure crossed exposure barrier", ledger.Phase)
			}
			if _, e := os.Stat(anchor + "/owned/report.json"); !os.IsNotExist(e) {
				t.Fatal("failure published aggregate")
			}
			if _, e := invoke(t, f, forbiddenOperations(t), "--out", anchor+"/owned"); e == nil {
				t.Fatal("failure implicitly retried")
			}
		})
	}
}
func TestCanonicalFixedReportsRejectAlteredBudgetAndMetadata(t *testing.T) {
	r := fitReport{1680, 40, 2120, 2120, 1, "fresh_zero", 1729, 32, .001, .01}
	m := modelAdapter{metadata: modelReport{TrainingSteps: 2120, InitializationSeed: 1729}}
	if !validFit(r, m, "fresh_zero") {
		t.Fatal("fixed report rejected")
	}
	for _, change := range []func(*fitReport){func(r *fitReport) { r.Samples-- }, func(r *fitReport) { r.Epochs-- }, func(r *fitReport) { r.Batches++ }, func(r *fitReport) { r.TrainingSteps = 4240 }, func(r *fitReport) { r.Seed++ }, func(r *fitReport) { r.Initialization = "warm" }, func(r *fitReport) { r.BatchSize++ }, func(r *fitReport) { r.LearningRate = .002 }, func(r *fitReport) { r.WeightDecay = .02 }, func(r *fitReport) { r.MeanLoss = math.NaN() }} {
		bad := r
		change(&bad)
		if validFit(bad, m, "fresh_zero") {
			t.Fatal("altered fit budget/report admitted")
		}
	}
}

func TestDirectorySyncFailurePreventsPendingFitAndPreservesActualCount(t *testing.T) {
	for failAt := 1; failAt <= 6; failAt++ {
		t.Run(fmt.Sprintf("sync-%d", failAt), func(t *testing.T) {
			t.Chdir(t.TempDir())
			f := ownedFixture(t)
			f.write(t)
			ops := forbiddenOperations(t)
			var events []string
			if failAt == 6 {
				ops = ownedOperations(t, f, &events)
				ops.fitMLP = forbiddenOperations(t).fitMLP
			}
			calls := 0
			ops.syncDirectory = func(root *os.Root) error {
				calls++
				if calls == failAt {
					return errStudy
				}
				return syncDirectory(root)
			}
			if _, e := invoke(t, f, ops, "--out", anchor+"/owned"); e == nil {
				t.Fatal("directory durability failure admitted")
			}
			if failAt <= 4 {
				if _, e := os.Stat(anchor + "/owned/fit-consumption.json"); !os.IsNotExist(e) {
					t.Fatal("output durability failure advanced to consumption")
				}
				return
			}
			data, e := os.ReadFile(anchor + "/owned/fit-consumption.json")
			var ledger consumption
			if e != nil || json.Unmarshal(data, &ledger) != nil {
				t.Fatal("directory sync failure ledger lost", e)
			}
			want := failAt - 5
			if ledger.FitCalls != want || ledger.FitInvocations != [2]int{want, 0} || !ledger.NoRetry {
				t.Fatal("failed directory sync consumed pending Fit", ledger)
			}
			if want == 0 {
				if ledger.Status != "failed_before_fit_invocation" || ledger.Phase != "cold_linear_fixed_fit_durability_guard" {
					t.Fatal("first guard failure status", ledger)
				}
			} else {
				if ledger.Status != "failed_after_fit_invocation_consumed" || ledger.Phase != "cold_mlp16_fixed_fit_durability_guard" || len(events) != 1 || events[0] != "fit_linear" {
					t.Fatal("second guard failure status", ledger, events)
				}
				if data, e := os.ReadFile(anchor + "/owned/linear.rsc"); e != nil || !bytes.Equal(data, f.linear) {
					t.Fatal("first saved model lost after directory sync failure", e)
				}
			}
		})
	}
}

func TestExistingPrivateStudyDirectoryMustBeOwnerOnly(t *testing.T) {
	t.Chdir(t.TempDir())
	if os.MkdirAll(anchor, 0755) != nil {
		t.Fatal("owned nonprivate directory")
	}
	root, e := os.OpenRoot(".")
	if e != nil {
		t.Fatal(e)
	}
	defer root.Close()
	if out, e := privateOutput(root, anchor+"/reject"); e == nil {
		out.Close()
		t.Fatal("existing nonprivate study directory admitted")
	}
	if _, e := os.Stat(anchor + "/reject"); !os.IsNotExist(e) {
		t.Fatal("private child created under nonprivate study directory")
	}
}

// Unlike the explicitly substituted phase tests, this smoke executes both
// native cold Fits. All 1680 training and 360 evaluation rows are created above
// in this test; their fits consume no real research-data budget.
func TestOwnedNativeTwoColdFitsEndToEnd(t *testing.T) {
	t.Chdir(t.TempDir())
	f := ownedFixture(t)
	f.write(t)
	if _, e := invoke(t, f, nativeOperations(), "--out", anchor+"/native-owned"); e != nil {
		t.Fatal("native owned-data study smoke", e)
	}
	data, e := os.ReadFile(anchor + "/native-owned/report.json")
	var report studyReport
	if e != nil || json.Unmarshal(data, &report) != nil {
		t.Fatal("native owned-data report", e)
	}
	if report.FitCalls != 2 || !report.FitsSavedBeforeEvaluation || report.ColdLinear.TrainingSteps != 2120 || report.ColdMLP.TrainingSteps != 2120 || report.PriorReference.TrainingSteps != 4240 || report.CPUProfile || report.Selection || report.Qualified || report.QualificationChanged || report.StateWrites != 0 {
		t.Fatal("native fixed history or research boundary", report.Fits)
	}
	for arm, fit := range report.Fits {
		init := "fresh_zero"
		if arm == 1 {
			init = statehintclaimsmlp.Initialization
		}
		if fit.Samples != 1680 || fit.Epochs != 40 || fit.Batches != 2120 || fit.TrainingSteps != 2120 || fit.BatchSize != 32 || fit.Seed != 1729 || fit.LearningRate != .001 || fit.WeightDecay != .01 || fit.Initialization != init || math.IsNaN(fit.MeanLoss) || math.IsInf(fit.MeanLoss, 0) {
			t.Fatal("native Fit recipe/history", arm, fit)
		}
	}
	ledgerData, e := os.ReadFile(anchor + "/native-owned/fit-consumption.json")
	var ledger consumption
	if e != nil || json.Unmarshal(ledgerData, &ledger) != nil || ledger.FitCalls != 2 || ledger.FitInvocations != [2]int{1, 1} || ledger.CompletedFits != [2]bool{true, true} || ledger.SavedModels != [2]bool{true, true} || ledger.Status != "completed_two_fixed_fits_no_selection" {
		t.Fatal("native actual Fit consumption", e, ledger)
	}
	linearData, e := os.ReadFile(anchor + "/native-owned/linear.rsc")
	if e != nil || len(linearData) != 73988 || digest(linearData) != report.ColdLinear.SHA || binary.LittleEndian.Uint64(linearData[16:24]) != 2120 {
		t.Fatal("native linear artifact/history", e)
	}
	mlpData, e := os.ReadFile(anchor + "/native-owned/mlp.rcm")
	if e != nil || len(mlpData) != 131972 || digest(mlpData) != report.ColdMLP.SHA || binary.LittleEndian.Uint64(mlpData[16:24]) != 2120 {
		t.Fatal("native MLP artifact/history", e)
	}
	if _, e := os.Stat(anchor + "/native-owned/cpu.pprof"); !os.IsNotExist(e) {
		t.Fatal("optional profile written while disabled")
	}
	for _, candidate := range []candidateReport{report.ColdLinear, report.ColdMLP} {
		if !candidate.ReloadByteExact || !candidate.ReloadPredictExact || !candidate.ReloadScoresExact || !candidate.ReadOnlyExact || candidate.PredictionCalls != 360 || candidate.ScoreCalls != 360 || candidate.ReloadPredictionCalls != 360 || candidate.ReloadScoreCalls != 360 {
			t.Fatal("native byte/Predict/Scores reload parity", candidate)
		}
	}
	ops := nativeOperations()
	linear, e := ops.loadLinear(linearData, 2120)
	if e != nil {
		t.Fatal("native linear reload", e)
	}
	mlp, e := ops.loadMLP(mlpData)
	if e != nil {
		t.Fatal("native MLP reload", e)
	}
	prior, e := ops.loadLinear(f.reference, 4240)
	if e != nil {
		t.Fatal("owned descriptive prior reload", e)
	}
	models := [3]modelAdapter{linear, mlp, prior}
	reports := [3]evaluationReport{report.ColdLinearEvaluation, report.ColdMLPEvaluation, report.PriorEvaluation}
	var computedCE [3]float64
	var generalCE [3]float64
	var unknownCE [3][2]float64
	var falsePositive [3][2][3]int
	for arm, m := range models {
		var proposed, correct [2][3]int
		var unknownCount [2]int
		for _, input := range ownedRows("dev", 180) {
			locale := localeIndex(input.Locale)
			score, e := m.scores(input.Text)
			if e != nil {
				t.Fatal("owned native score", e)
			}
			prediction, e := m.predict(input.Text)
			if e != nil {
				t.Fatal("owned native prediction", e)
			}
			isGeneral := strings.Compare(input.Family, "owned-dev-120") >= 0
			for head, target := range input.Targets {
				k, ok := statehintclaims.StateIndex(statehintclaims.State(target))
				if !ok {
					t.Fatal("owned target")
				}
				prob := score.Probabilities[head][k]
				ce := -math.Log(math.Max(prob, 1e-15))
				computedCE[arm] += ce / (3 * 360)
				if isGeneral {
					generalCE[arm] += ce / (3 * 120)
				}
				if target == "unknown" {
					unknownCE[arm][locale] += ce
					unknownCount[locale]++
				}
				if prediction.Heads[head].State == statehintclaims.True {
					proposed[locale][head]++
					if target == "true" {
						correct[locale][head]++
					} else {
						falsePositive[arm][locale][head]++
					}
				}
			}
		}
		if math.Abs(computedCE[arm]-reports[arm].MeanCE) > 1e-12 {
			t.Fatal("native mean three-head CE aggregation", arm, computedCE[arm], reports[arm].MeanCE)
		}
		for locale := 0; locale < 2; locale++ {
			unknownCE[arm][locale] /= float64(unknownCount[locale])
			if reports[arm].Locales[locale].TrueProposed != proposed[locale] || reports[arm].Locales[locale].TrueCorrect != correct[locale] || reports[arm].Locales[locale].TrueFalsePositive != falsePositive[arm][locale] || math.Abs(reports[arm].Locales[locale].UnknownTargetCE-unknownCE[arm][locale]) > 1e-12 {
				t.Fatal("native locale gated-true FP/unknown CE plumbing", arm, locale)
			}
		}
	}
	if math.Abs(report.Primary.Difference-(computedCE[1]-computedCE[0])) > 1e-12 || math.Abs(report.Primary.StrataDifference[1]-(generalCE[1]-generalCE[0])) > 1e-12 || report.Primary.Lineages != [2]int{40, 20} {
		t.Fatal("native paired delta/group denominators")
	}
	primary := report.Primary.ConfidenceInterval[1] < 0
	general := generalCE[1]-generalCE[0] <= 0
	expected := primary && general
	if report.Progress.PrimaryCIUpperBelowZero != primary || report.Progress.GeneralCENonIncreasing != general {
		t.Fatal("native primary/general conditions")
	}
	for locale := 0; locale < 2; locale++ {
		unknownLower := unknownCE[1][locale] < unknownCE[0][locale]
		if report.Progress.UnknownCELower[locale] != unknownLower {
			t.Fatal("native unknown CE condition")
		}
		expected = expected && unknownLower
		for head := 0; head < 3; head++ {
			noAdded := falsePositive[1][locale][head] <= falsePositive[0][locale][head]
			if report.Progress.NoAddedTrueFalsePositives[locale][head] != noAdded {
				t.Fatal("native FP condition")
			}
			expected = expected && noAdded
		}
	}
	if report.Progress.ResearchProgress != expected {
		t.Fatal("native frozen conditions combined incorrectly")
	}
}
