// Copyright 2026 SWYG. SPDX-License-Identifier: Apache-2.0
package claimsdemo

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"io"
	"net"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/teamswyg/laya-tools/pkg/statehintclaims"
)

func TestListenMustBeExplicitLoopbackWithNumericPort(t *testing.T) {
	for _, address := range []string{"127.0.0.1:8877", "localhost:8877", "[::1]:8877", "127.0.0.1:0"} {
		if _, err := normalizeListen(address); err != nil {
			t.Fatalf("rejected %q: %v", address, err)
		}
	}
	for _, address := range []string{":8877", "0.0.0.0:8877", "[::]:8877", "192.0.2.1:8877", "example.invalid:8877", "localhost", "localhost:http", "localhost:-1", "localhost:65536", "localhost:", "localhost:8877/path"} {
		if _, err := normalizeListen(address); err == nil {
			t.Fatalf("accepted %q", address)
		}
	}
}

func TestLocalhostBindsAnExplicitLoopbackIP(t *testing.T) {
	address, err := normalizeListen("LOCALHOST:0")
	if err != nil || address != "127.0.0.1:0" {
		t.Fatalf("localhost was not normalized: %q %v", address, err)
	}
	listener, err := net.Listen("tcp", address)
	if err != nil {
		t.Fatal(err)
	}
	defer listener.Close()
	bound, ok := listener.Addr().(*net.TCPAddr)
	if !ok || !bound.IP.IsLoopback() || !bound.IP.Equal(net.ParseIP("127.0.0.1")) {
		t.Fatalf("unexpected bound address: %v", listener.Addr())
	}
}

func TestStartupRejectsMissingModelBadArgumentsAndPublicListen(t *testing.T) {
	for _, args := range [][]string{nil, {"--model", "missing", "extra"}, {"--model", "missing", "--listen", "0.0.0.0:8877"}, {"--model", "missing", "--model-sha256", "invalid"}, {"--unexpected"}} {
		var out bytes.Buffer
		if err := run(context.Background(), args, &out, io.Discard); err == nil || out.Len() != 0 {
			t.Fatalf("invalid startup succeeded: %v", args)
		}
	}
	var help bytes.Buffer
	if err := run(context.Background(), []string{"--help"}, io.Discard, &help); err != nil || !strings.Contains(help.String(), "-model") {
		t.Fatal("help failed")
	}
}

func TestModelHashIsCheckedBeforeArtifactLoad(t *testing.T) {
	// Deliberately corrupt, newly generated bytes prove the expected hash check
	// takes precedence over format loading; no model inference or training occurs.
	path := filepath.Join(t.TempDir(), "corrupt.rsc")
	data := bytes.Repeat([]byte{0x3a}, statehintclaims.ArtifactBytes)
	if err := os.WriteFile(path, data, 0600); err != nil {
		t.Fatal(err)
	}
	if _, _, err := loadModel(path, strings.Repeat("0", 64)); err == nil || !strings.Contains(err.Error(), "SHA-256 mismatch") {
		t.Fatalf("expected hash check first, got %v", err)
	}
	sum := sha256.Sum256(data)
	if _, _, err := loadModel(path, hex.EncodeToString(sum[:])); err == nil || !strings.Contains(err.Error(), "invalid or corrupted") || strings.Contains(err.Error(), path) {
		t.Fatalf("matching hash did not reject corrupt format safely: %v", err)
	}
}

func TestStartupRejectsUntrainedScaffoldAndMalformedFiles(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "untrained-scaffold.rsc")
	// The format-only untrained scaffold is exclusively a rejection fixture.
	// It is never used as a demo model, fitted, warmed, or invoked for inference.
	var scaffold bytes.Buffer
	if err := statehintclaims.NewModel().Save(&scaffold); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, scaffold.Bytes(), 0600); err != nil {
		t.Fatal(err)
	}
	if _, _, err := loadModel(path, ""); err == nil || !strings.Contains(err.Error(), "untrained scaffold") {
		t.Fatalf("untrained scaffold was not rejected: %v", err)
	}
	if _, _, err := loadModel(path, strings.Repeat("z", 64)); err == nil || !strings.Contains(err.Error(), "64 hexadecimal") {
		t.Fatal("malformed expected checksum accepted")
	}
	for name, data := range map[string][]byte{"short.rsc": []byte("RSC"), "extra.rsc": append(scaffold.Bytes(), 0)} {
		bad := filepath.Join(dir, name)
		if err := os.WriteFile(bad, data, 0600); err != nil {
			t.Fatal(err)
		}
		if _, _, err := loadModel(bad, ""); err == nil || strings.Contains(err.Error(), bad) {
			t.Fatal("malformed model accepted or error exposed its path")
		}
	}
	for _, bad := range []string{dir, filepath.Join(dir, "does-not-exist.rsc")} {
		if _, _, err := loadModel(bad, ""); err == nil || strings.Contains(err.Error(), bad) {
			t.Fatal("unavailable/nonregular model accepted or error exposed its path")
		}
	}
}
